import numpy as nm
from numpy import pi
a=nm.arange(20).reshape(4,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(type(a))
b=nm.array([6.5,7,8])
print(b)
print(type(b))
print(b.dtype)
c=nm.array([[1,2],[3,4]],dtype=complex)
print(c)
print(nm.zeros((4,5)))
d=nm.ones((2,3,4),dtype=nm.int16)  #2 for number of matrices then 3 and 4 for row columns.
print(d)
e=nm.empty((3,4))
print(e)
print("-"*10)
f=nm.arange(10,30,5)
print(f)
print("-"*10)
g=nm.arange(0,2,0.5)
print(g)
print("-"*10)
h=nm.linspace(0,2,9)
print(h)
print("-"*10)
i=nm.linspace(0,2 * pi,100)
j=nm.sin(i)
print(j)
k=nm.arange(60).reshape(3,2,5,2)
print(k)
print(k.shape)
print(k.ndim)
print(k.size)